# Generated by Django 3.0.5 on 2020-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50, unique=True)),
                ('facultyname', models.CharField(max_length=50)),
                ('fees', models.FloatField()),
                ('stardate', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('classtime', models.TimeField()),
            ],
        ),
    ]
