# Generated by Django 3.0.5 on 2020-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
